//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class fetchitEntities : DbContext
    {
        public fetchitEntities()
            : base("name=fetchitEntities")
        {
            Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CommentModel> CommentModels { get; set; }
        public virtual DbSet<FeedbackModel> FeedbackModels { get; set; }
        public virtual DbSet<FeedbackStatusModel> FeedbackStatuses { get; set; }
        public virtual DbSet<IssueDetailModel> IssueDetailModels { get; set; }
        public virtual DbSet<IssueModel> IssueModels { get; set; }
        public virtual DbSet<IssueStatusModel> IssueStatuses { get; set; }
        public virtual DbSet<LogModel> LogModels { get; set; }
        public virtual DbSet<NotificationModel> NotificationModels { get; set; }
        public virtual DbSet<NotificationStatusModel> NotificationStatuses { get; set; }
        public virtual DbSet<PaymentModel> PaymentModels { get; set; }
        public virtual DbSet<PaymentStatusModel> PaymentStatuses { get; set; }
        public virtual DbSet<PaymentTypeModel> PaymentTypeModels { get; set; }
        public virtual DbSet<ProfileLevelModel> ProfileLevelModels { get; set; }
        public virtual DbSet<ProfileModel> ProfileModels { get; set; }
        public virtual DbSet<ProfileStatusModel> ProfileStatuses { get; set; }
        public virtual DbSet<ProfileVerificationTypeModel> ProfileVerificationTypeModels { get; set; }
        public virtual DbSet<ReportModel> ReportModels { get; set; }
        public virtual DbSet<SessionModel> SessionModels { get; set; }
        public virtual DbSet<TaskLocationInfoModel> TaskLocationInfos { get; set; }
        public virtual DbSet<TaskModel> TaskModels { get; set; }
        public virtual DbSet<TaskStatusModel> TaskStatuses { get; set; }
    }
}
