//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeedbackModel
    {
        public int FeedbackId { get; set; }
        public byte FeedbackRating { get; set; }
        public string FK_FeedbackNotificationReferenceId { get; set; }
        public string FeedbackComment { get; set; }
        public int FK_FeedbackForTask { get; set; }
        public int FK_FeedbackStatus { get; set; }
    
        public virtual FeedbackStatusModel FeedbackStatus { get; set; }
        public virtual TaskModel Task { get; set; }
    }
}
