//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class IssueDetailModel
    {
        public int IssueDetailId { get; set; }
        public int FK_Issue { get; set; }
        public bool IssueDetailFromCreator { get; set; }
        public byte[] IssueImage { get; set; }
        public string IssueDetailText { get; set; }
    
        public virtual Issue Issue { get; set; }
    }
}
