//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api.EntityFramework
{
    using System.Collections.Generic;
    
    public partial class IssueStatusModel
    {
        public IssueStatusModel()
        {
            this.Issues = new HashSet<IssueModel>();
        }
    
        public int IssueStatusId { get; set; }
        public string IssueStatus { get; set; }
    
        public virtual ICollection<IssueModel> Issues { get; set; }
    }
}
