//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api.EntityFramework
{
    public partial class LogModel
    {
        public int LogId { get; set; }
        public string LogMessage { get; set; }
        public System.DateTime LogTime { get; set; }
    }
}
