//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api.EntityFramework
{
    using System.Collections.Generic;
    
    public partial class ProfileStatusModel
    {
        public ProfileStatusModel()
        {
            this.Profiles = new HashSet<ProfileModel>();
        }
    
        public int ProfileStatusId { get; set; }
        public string ProfileStatus { get; set; }
    
        public virtual ICollection<ProfileModel> Profiles { get; set; }
    }
}
