//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportModel
    {
        public int ReportId { get; set; }
        public int FK_ReportingProfile { get; set; }
        public string ReportMessage { get; set; }
        public System.DateTime ReportTime { get; set; }
        public int FK_ReportedProfile { get; set; }
    
        public virtual ProfileModel ReportedProfile { get; set; }
        public virtual ProfileModel ReportingProfile { get; set; }
    }
}
