//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api.EntityFramework
{
    using System;

    public partial class SessionModel
    {
        public int SessionId { get; set; }
        public int FK_ProfileId { get; set; }
        public string SessionIp { get; set; }
        public System.DateTime SessionStart { get; set; }
        public Nullable<System.DateTime> SessionEnd { get; set; }
    
        public virtual ProfileModel Profile { get; set; }
    }
}
