//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskModel
    {
        public TaskModel()
        {
            this.Comments = new HashSet<CommentModel>();
            this.Feedbacks = new HashSet<FeedbackModel>();
            this.Issues = new HashSet<Issue>();
            this.Payments = new HashSet<PaymentModel>();
            this.TaskLocationInfos = new HashSet<TaskLocationInfoModel>();
        }
    
        public int TaskId { get; set; }
        public string FK_TaskNotificationReferenceId { get; set; }
        public int FK_TaskMaster { get; set; }
        public Nullable<int> FK_TaskFetcher { get; set; }
        public string TaskDescription { get; set; }
        public System.DateTime TaskTimeCreated { get; set; }
        public System.DateTime TaskDeadline { get; set; }
        public decimal TaskItemPrice { get; set; }
        public decimal TaskFee { get; set; }
        public int FK_TaskStatus { get; set; }
        public string TaskEndPointAddress { get; set; }
    
        public virtual ICollection<CommentModel> Comments { get; set; }
        public virtual ICollection<FeedbackModel> Feedbacks { get; set; }
        public virtual ICollection<Issue> Issues { get; set; }
        public virtual ICollection<PaymentModel> Payments { get; set; }
        public virtual ProfileModel FetcherProfile { get; set; }
        public virtual ProfileModel MasterProfile { get; set; }
        public virtual ICollection<TaskLocationInfoModel> TaskLocationInfos { get; set; }
        public virtual TaskStatus TaskStatus { get; set; }
    }
}
