//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api.EntityFramework
{
    public partial class TaskLocationInfoModel
    {
        public int TaskLocationInfoId { get; set; }
        public int FK_TaskId { get; set; }
        public string TaskLocationAddress { get; set; }
    
        public virtual TaskModel Task { get; set; }
    }
}
