//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FetchItClassLib.Persistence.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommentModel
    {
        public int CommentId { get; set; }
        public string CommentText { get; set; }
        public System.DateTime CommentDateCreated { get; set; }
        public int FK_CommentCreatorProfileId { get; set; }
        public int FK_CommentInTaskId { get; set; }
    
        public virtual ProfileModel Profile { get; set; }
        public virtual TaskModel Task { get; set; }
    }
}
