//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FetchItClassLib.Persistence.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class IssueModel
    {
        public int IssueId { get; set; }
        public bool IssueDidTaskMasterCreate { get; set; }
        public string IssueTitle { get; set; }
        public string IssueDescription { get; set; }
        public bool IssueStatus { get; set; }
        public string IssueSolution { get; set; }
        public System.DateTime IssueDateCreated { get; set; }
        public int FK_IssueInTaskId { get; set; }
    
        public virtual TaskModel Task { get; set; }
    }
}
