//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FetchItClassLib.Persistence.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentStatusModel
    {
        public PaymentStatusModel()
        {
            this.Payments = new HashSet<PaymentModel>();
        }
    
        public int PaymentStatusId { get; set; }
        public string PaymentStatus { get; set; }
    
        public virtual ICollection<PaymentModel> Payments { get; set; }
    }
}
