//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FetchItClassLib.Persistence.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentModel
    {
        public int PaymentId { get; set; }
        public int FK_PaymentStatusId { get; set; }
        public decimal PaymentAmount { get; set; }
        public int FK_PaymentForTaskID { get; set; }
        public int FK_PaymentTypeID { get; set; }
    
        public virtual TaskModel Task { get; set; }
        public virtual PaymentStatusModel PaymentStatus { get; set; }
        public virtual PaymentTypeModel PaymentType { get; set; }
    }
}
