//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FetchItClassLib.Persistence.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfileLevelModel
    {
        public ProfileLevelModel()
        {
            this.Profiles = new HashSet<ProfileModel>();
        }
    
        public int LevelId { get; set; }
        public string Level { get; set; }
    
        public virtual ICollection<ProfileModel> Profiles { get; set; }
    }
}
