//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FetchItClassLib.Persistence.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfileModel
    {
        public ProfileModel()
        {
            this.Comments = new HashSet<CommentModel>();
            this.TasksFetcher = new HashSet<TaskModel>();
            this.TaskMaster = new HashSet<TaskModel>();
        }
    
        public int ProfileId { get; set; }
        public string ProfileName { get; set; }
        public string ProfileAddress { get; set; }
        public string ProfilePhone { get; set; }
        public string ProfileMobile { get; set; }
        public string ProfilePassword { get; set; }
        public string ProfileEmail { get; set; }
        public int FK_ProfileStatusId { get; set; }
        public string ProfileLastLoggedIn { get; set; }
        public int FK_ProfileLevelId { get; set; }
        public bool ProfileIsVerified { get; set; }
        public string ProfileImage { get; set; }
        public string ProfileText { get; set; }
    
        public virtual ICollection<CommentModel> Comments { get; set; }
        public virtual ProfileLevelModel ProfileLevel { get; set; }
        public virtual ProfileStatusModel ProfileStatus { get; set; }
        public virtual ICollection<TaskModel> TasksFetcher { get; set; }
        public virtual ICollection<TaskModel> TaskMaster { get; set; }
    }
}
