//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FetchItClassLib.Persistence.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskModel
    {
        public TaskModel()
        {
            this.Comments = new HashSet<CommentModel>();
            this.Feedback = new HashSet<FeedbackModel>();
            this.Issues = new HashSet<IssueModel>();
            this.Payment = new HashSet<PaymentModel>();
        }
    
        public int TaskId { get; set; }
        public int FK_TaskMasterProfileId { get; set; }
        public int FK_TaskFetcherProfileId { get; set; }
        public string TaskDescription { get; set; }
        public System.DateTime TaskDateCreated { get; set; }
        public System.DateTime TaskDeadline { get; set; }
        public bool TaskIsActive { get; set; }
        public bool TaskIsSuspended { get; set; }
        public bool TaskIsCompleted { get; set; }
    
        public virtual ICollection<CommentModel> Comments { get; set; }
        public virtual ICollection<FeedbackModel> Feedback { get; set; }
        public virtual ICollection<IssueModel> Issues { get; set; }
        public virtual ICollection<PaymentModel> Payment { get; set; }
        public virtual ProfileModel ProfileTaskFetcher { get; set; }
        public virtual ProfileModel ProfileTaskMaster { get; set; }
    }
}
